on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: custom checkout
        run: |
          /usr/bin/git config --global --add safe.directory /home/runner/work/hexamaze/hexamaze
          git clone https://github.com/meXc/hexamaze /home/runner/work/hexamaze/hexamaze

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Specify the Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Running example generation
        run: |
          git checkout origin/master
          git fetch --tags
          python ./hexamaze/mazing.py --seed 1323150628 --version-Output --output example.png
          python ./hexamaze/mazing.py --seed 1323150628 --debug --output example-debug.png
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add example.png example-debug.png ./hexamaze/version.ini
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
            exit 0
          fi
          git commit --amend --no-edit
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin main
